### ISSUE TITLE
Co-routine error: 'Task exception was never retrieved future'

### ISSUE THREAD

**Issue by kstohr** [kognate/watson_speech_to_text_websockets#1]
The sample code worked fine on the short audio snippets provided in the test case, but seems to fail with error code 1011 on a longer file. I think the issue may be related to the call to close the websocket connection while handling the response.  

Background: I am building a tool that transcribes public meetings. I don't need real-time transcription or interim results. I do need speaker detection. The audio files in this use case are typically 100 - 400mb each. My current approach is to split the audio files into shorter 10min clips, then stream those clips over websockets to Watson. My preferred result is simply to receive the full, final hypothesis as a json serializable object.  If this is the wrong approach, please advise. 

Python 3.5.2 / Chrome v. 58.0.3029 / OSX 10.11.6

Any help in getting a websocket connection up and running hugely appreciated. 

The sample code on the short sample wav file (641kb) works seamlessly: 
```
import os
from watson_speech_to_text_websockets import WSSpeechToTextV1
recordings = ["./recordings/{0}".format(x)
              for x
              in os.listdir('./recordings')]

username = os.environ['WATSON_SPEECH_USERNAME']
password = os.environ['WATSON_SPEECH_PASSWORD'] 

recordings[1]
Out[4]:
'./recordings/0001.wav'

ws = WSSpeechToTextV1(username=username, password=password)
results = ws.recognize(file_name=recordings[1],
                       content_type="audio/wav",
                       keywords_threshold=0.6,
                       keywords=['welcome'],
                       content_callback=lambda x: print(x),
                       inactivity_timeout=None,
                       #speaker_labels=True
                      )
print(results)

```
When I adapt the code and change the args to get the results on a longer (5 min / 20mb) clip, I get the following error message. 

Here is the adapted code: 
```
ws = WSSpeechToTextV1(username=username, password=password)
results = ws.recognize(file_name=recordings[-1],
                       content_type="audio/wav",
                       #keywords_threshold=0.6,
                       #keywords=['welcome'],
                       content_callback=None,
                       inactivity_timeout=-1, #ensure timeout does not occur due to silence
                       word_confidence=True,
                       timestamps=True,
                       speaker_labels=True, 
                       smart_formatting=True,
                      )

print(results)
```
Here is the error message: 
```
Task exception was never retrieved
future: <Task finished coro=<WSSpeechToTextV1._send_fileobj() done, defined at /Users/kate/dev/watson_speech_to_text_websockets-master/watson_speech_to_text_websockets/ws_speech_to_text_v1.py:84> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/Users/kate/dev/watson_speech_to_text_websockets-master/watson_speech_to_text_websockets/ws_speech_to_text_v1.py", line 90, in _send_fileobj
    await wsocket.send(buffer)
  File "/Users/kate/dev/pblc_dev/venv3_pblc/lib/python3.5/site-packages/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "/Users/kate/dev/pblc_dev/venv3_pblc/lib/python3.5/site-packages/websockets/protocol.py", line 402, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
````
Playing around with your code, I noticed the 'websocket.close()' call is included in the routine for handling responses which was cutting off the response.  I tried moving that into a separate action using the second 'state':'listening' response to close the connection instead. Also, tried gathering responses using the asyncio.gather() method. See attached.  Still no love.  

SCRIPT
[ws_speech_to_text_v1_adpated.txt](https://github.com/kognate/watson_speech_to_text_websockets/files/1062432/ws_speech_to_text_v1_adpated.txt)
: 
OUTPUT: 
[test.py.pdf](https://github.com/kognate/watson_speech_to_text_websockets/files/1062426/test.py.pdf)

Side note/suggestion, I realize this was written to support real-time transcription, but this script might be more versatile if you included "interim results' as an argument that can be adjusted.

**Comment by kognate** [comment]
This repository will be removed from Github on Jan 28 and is no longer being maintained or developed.  I see you have a comment in the actual watson SDK, I would recommend continuing the discussion there.
